[package]
name = "hikari"
version = "0.1.0"
edition = "2021"
authors = ["Kalyan Mudumby"]
description = ""
repository = "https://github.com/theinhumaneme/hikari"
rust-version = "1.80.0"
readme = "README.md"

[dependencies]
clap = { version = "4.5.21", features = ["cargo"] }
dotenvy = "0.15.7"
ring = "0.17.8"
serde = "1.0.215"
serde_json = "1.0.133"
serde_yaml = "0.9.34"

[profile.dev]
lto = false
opt-level = 0

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
